INSERT INTO  "trazos"."paso" ("nombre", "descripcion", "esta_terminado", "paso_numero", "id_usuario", "id_rol", "id_trazo") VALUES
('paso 1', 'Descripcion de paso 1', 'false', 1, 2, 2, 1),
('paso 2', 'Descripcion de paso 2', 'false', 2, 2, 2, 1),
('paso 3', 'Descripcion de paso 3', 'false', 3, 2, 2, 1),
('paso 1', 'Descripcion de paso 1', 'true', 1, 2, 2, 2),
('paso 2', 'Descripcion de paso 2', 'false', 2, 2, 2, 2),
('paso 1', 'Descripcion de paso 1', 'true', 1, 2, 2, 3),
('paso 1', 'Descripcion de paso 1', 'true', 1, 1, 2, 4),
('paso 2', 'Descripcion de paso 2', 'false', 2, 1, 1, 4),
('paso 3', 'Descripcion de paso 3', 'false', 3, 1, 2, 5),
('paso 1', 'Descripcion de paso 1', 'false', 1, 1, 1, 5),
('paso 2', 'Descripcion de paso 2', 'false', 2, 1, 1, 5);